/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "essaisupabase"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc4MjA3NzI4MCwiZXhwIjo0OTM3NzUwODgwLCJyb2xlIjoiYW5vbiJ9.TQVfTJykr8dQlE1yW6OM9_1t3VvO5AZWBypEhNFuvuI"
export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || `https://essaisupabase.ippoo-aptdc.com`
